"""add_extraction_fields_to_projects

Revision ID: 3682d05f65f3
Revises: db3d30634f4e
Create Date: 2026-07-02 23:41:15.830984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3682d05f65f3'
down_revision: Union[str, None] = 'db3d30634f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('extraction_status', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('total_files', sa.BigInteger(), nullable=True))
    op.add_column('projects', sa.Column('total_folders', sa.BigInteger(), nullable=True))
    op.add_column('projects', sa.Column('extraction_time_ms', sa.BigInteger(), nullable=True))
    op.add_column('projects', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'extracted_at')
    op.drop_column('projects', 'extraction_time_ms')
    op.drop_column('projects', 'total_folders')
    op.drop_column('projects', 'total_files')
    op.drop_column('projects', 'extraction_status')
    # ### end Alembic commands ###
